version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Connection #2"
description: "Connection #2 is a visual experiment based on Connection #1 which create images based on user interacts and some random number"
url: "http://behrooz-tahanzadeh.github.io/connection-2/"
date: "August 2014"
googleAnalyticsCode: "UA-40560087-5"
